- hosts: all

  tasks:
    - name: Copy file
      copy:
        src: test.txt
        dest: /tmp/text.txt

    - name: Create a directory if it does not exist
      file:
        path: /etc/some_directory
        state: directory
        mode: '0755'

    - name: Install git
      apt:
        package: git
        state: present

    - name: Clone repo
      git:
        repo: https://github.com/codex-team/workflow.git
        dest: ~/workflow
